name: Newman API Test - GET /api/products

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies & Newman
      run: |
        cd backend
        npm install
        npm install -g newman wait-port

    - name: Start Backend Provider
      run: |
        cd backend
        npm run dev &
        wait-port 3000 --timeout 60000

    - name: Run Newman Tests
      run: |
        newman run mini-products.postman_collection.json \
          -e mini-local.postman_environment.json \
          -d mini-products.data.json \
          -r "cli,json" \
          --reporter-json-export mini-newman-report.json

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: newman-report
        path: mini-newman-report.json